### PR TITLE
Extra pip features

### PR DESCRIPTION
**Pull request by nottrobin**
New features for installing pip requirements, and simplify config:
- Config setting to read and install pip requirements from a file, optionally providing your own pip-cache folder
- Create new config-options so you don't need to customise playbook.yml - e.g. for nagios check string, and for apt dependencies

### CODE REVIEW

**Comment by absoludity** [comment]
Hi Robin - sorry it's taken so long for me to get back on this pull request (hectic, moving countries, excuses excuses).

I think we've already chatted about these points on irc since, but just in case I'm mis-remembering:

RE the new config options so you don't need to customise the playbook (apt_dependencies, archive_filename, code_assets_uri, wsgi_application, nagios_index_content), I'm actually specifically avoiding doing that for the example bootstrap app. I'd initially gone down the road of trying to create a general wsgi charm for multiple services where you just configure the wsgi application and archive filename, but found that I'd either have to force devs to handle settings in exactly the same way in every app (which isn't realistic for us at the moment), or modify the charm for each service anyway. In the end, for my use-case, it's much simpler to have a small shell of a service-specific charm, with a simple-as-possible config.yaml, which is why I'm demoing and encouraging that with the bootstrap. If you've solved those issues, let me know!

The pip requirements config options fall into the same basket too - in the same way that installing app specific apt dependencies is the charms responsibility, so would custom pip packages - ie., just an extra task in the charm's playbook as you've done.

Let me know if I've overlooked something!

**Comment by nottrobin** [comment]
Okay that's fine. I find it much more convenient to be able to customise the charm through the standard config options, but I'll happily keep this in my own fork.

There were two other changes in my pull request that you haven't covered:
- I removed the "app_label" parameter from playbooks.yaml and instead defaulted it to the unit name
- I removed the "code_archive" parameter, which is built using "build_label", in favour of keeping separate "build_label" and "archive_filename" separate - since most of the time you were using "code_archive | dirname" anyway, which is simply the same as "build_label".

Another change which I've made in my local version is to set the default port inside wsgi-app to 8080 and then removing it from playbook.yaml - as it wasn't clear to me why you are defaulting port to 8081, and then overriding it.

**Comment by absoludity** [comment]
Oh yes. +1 for defaulting app_label to unit name (great for the example as it simplifies things even more). And also +1 for separate build_label and archive_filename for the wsgi_app role.

Thanks!

**Comment by nottrobin** [comment]
Super old. Closing.

**Pull request closed without merging**
